### PR TITLE
Major refactoring of Diagnostics module

### PR DESCRIPTION
**Pull request by JulioAPeraza**
This is part of the refactoring issue #772, to reduce some of the duplicated code as was pointed out here #765.

Changes proposed in this pull request:

- Create a new base class `Diagnostics`, to reduce duplicated code.  
- In addition, we plan to change the AttributeError to a Warning when using pairwise Estimators and return only the clusters table as suggested here #761 by @jdkent.

### CODE REVIEW

**Comment by JulioAPeraza** [comment]
@jdkent To avoid the breaking change, do you think it would be a good idea if instead, we return an empty contribution table when the estimator is not supported, similar to what we do when the number of clusters is 0:
https://github.com/neurostuff/NiMARE/blob/08cbfad56e010f872bb858fca43e54f8bdc43bbe/nimare/diagnostics.py#L167-L170
In that case, we won't need to have the extra flag `return_clusters_table_only`.

**Comment by JulioAPeraza** [comment]
Thanks! 
I've added the suggestions and documented the new changes. I also added a new test to improve coverage.

**Review by jdkent — APPROVED** [review]
Looked it over, changes look good and you test it with one of the pairwise estimators, LGTM.

**Comment by JulioAPeraza** [comment]
thanks!

**Pull request merged**
