### PR TITLE
[FIX] Fix missing parameter q of FDRCorrector

### LINKED ISSUE #181: Missing q parameter in FDRCorrector class
Hi, I think I found a small error in the `nimare.correct.FDRCorrector` class. The transform method of the class is looking at a parameter `q` https://github.com/neurostuff/NiMARE/blob/e17629fb0793a593a9b244ca4fe9dbbc3412f592/nimare/correct/correct.py#L66 
which does not exist in that class.
https://github.com/neurostuff/NiMARE/blob/e17629fb0793a593a9b244ca4fe9dbbc3412f592/nimare/correct/correct.py#L56-L58

The PR will follow.

### PR DESCRIPTION
**Pull request by alexprz**
Closes #181.

I added the missing parameter `q` in the `__init__`function of the `nimare.correct.FDRCorrector`.

The other alternative would have been to read this parameter from the existing `self.parameters` dictionary but I found it weirder since `q` is a required argument.

### CODE REVIEW

**Comment by tsalo** [comment]
Thank you for catching this! Would you mind changing `q` to `alpha` throughout the class, as that's what we use in other FDR implementations in NiMARE?

**Comment by alexprz** [comment]
Done! I also changed the doc consequently.

**Comment by nicholst** [comment]
+1 for alpha over q  :)

**Comment by tsalo** [comment]
@alexprz Everything looks good to me, but before I merge, do you want to add yourself to the Zenodo file?

**Comment by alexprz** [comment]
It was only a small change but I would appreciate it thanks!

**Comment by tsalo** [comment]
Great! Merging now.

**Pull request merged**
