### PR TITLE
[DOC] Draft boilerplates for ALE and SCALE workflows

### PR DESCRIPTION
**Pull request by tsalo**
Progress on #36.

Changes proposed in this pull request:

- Add boilerplates for ALE and SCALE CLI workflows.
- Add Colin MNI template (used by GingerALE) and make default for ALE and SCALE.
- Support both `-h` and `--help` for nimare CLI help.

### CODE REVIEW

**Comment by tsalo** [comment]
@62442katieb @mriedel56 @kimberlylray You have written up ALE meta-analyses for publications in the past. Would you mind weighing in on the boilerplates? Is there any more information that we should provide?

**Comment by 62442katieb** [comment]
Of course! I’ll take a look later today.

**Comment by kimberlylray** [comment]
Hey Taylor, heres a list of additional details that might be useful: 
1. number of foci contributing to ALE
2. total number of subjects across all studies in ALE
3. does NiMare ask for a minimum cluster volume like gingerALE does? 
4. specify the gray matter template - Im assuming its one of the MNI?

Also - is the contrast between two ALEs going to be an option?

**Comment by tsalo** [comment]
@kimberlylray Thank you!

I can add each of those, since we have all of that information.

Contrast analysis _will_ be supported, but currently is not. Technically, the code is already there, but it's untested and I don't know if it's any good. Once we've tested it, I'll add in an optional `sleuth_file2` argument to the ALE CLI. If you have a boilerplate (or even an example from a publication) for contrast analyses that I can work off of, that would be extremely helpful.

**Pull request merged**
