### PR TITLE
Optimize locating coordinates in convert_neurosynth_to_dataset

### LINKED ISSUE #666: Speed up `convert_neurosynth_to_dataset`
I wonder if we could speed up this function by providing the inputs in a way that is more amenable to the way it is internally represented. 

This is not a very concrete suggestion but just an observation that this is particularly slow and memory heavy.

### PR DESCRIPTION
**Pull request by ryanhammonds**
Closes #666.

Changes proposed in this pull request:

- small optimization that reduces `convert_neurosynth_to_dataset` runtime from ~7min to ~3min.
- I profiled these changes with:

```python
from nimare.extract import fetch_neurosynth
from nimare.io import convert_neurosynth_to_dataset

neurosynth_db = fetch_neurosynth(
    data_dir='.',
    version="7",
    source="abstract",
    vocab="terms",
)[0]

neurosynth_dset = convert_neurosynth_to_dataset(
    coordinates_file=neurosynth_db["coordinates"],
    metadata_file=neurosynth_db["metadata"],
    annotations_files=neurosynth_db["features"],
    feature_groups=['alzheimer']
)
```

### CODE REVIEW

**Review by tsalo — APPROVED** [review]
These changes look good to me, and I was able to reproduce the profiling results locally. @adelavega, since you opened the original issue, I wanted to see if this is what you were thinking of before merging.

**Comment by tsalo** [comment]
Also, @ryanhammonds, do you want to add yourself to the Zenodo file?

**Comment by ryanhammonds** [comment]
Thanks @tsalo! No need to add me to the Zenodo file. Maybe if I make larger contributions in the future.

**Review by adelavega — APPROVED** [review]
Nice. LGTM. I'm a bit surprised how much of a difference using numpy instead of pandas makes. Good lesson for other parts of the package.

**Comment by tsalo** [comment]
Great, thanks @adelavega!

Merging now. Thanks again for the contribution @ryanhammonds.

**Pull request merged**
