### PR TITLE
Enhance LDA annotator

### PR DESCRIPTION
**Pull request by JulioAPeraza**
Closes None.

Changes proposed in this pull request:

- Add the parallelization option and use it in the `LatentDirichletAllocation` model.
- Switch `learning_method` from `online` to the default `batch`.

### CODE REVIEW

**Comment by JulioAPeraza** [comment]
@tsalo Do you think it would be Ok to add support for running LDA with `counts_df` as an input in this PR?

Also, I was wondering if it would be possible to initialize and fit both the LDA and GCLDA annotators more uniformly. For example, 
Init LDAModel with:
```
n_topics, max_iter=1000, alpha=None, beta=0.001, text_column="abstract", n_cores=1
```
Init GCLDAModel with
```
n_topics=100, n_iters=10000, loglikely_freq=10, n_regions=2, symmetric=True, alpha=0.1, beta=0.01, gamma=0.01, delta=1.0, dobs=25, roi_size=50.0, seed_init=1
```
And fitting the models with `fit(self, dset, counts_df=None) `.

**Comment by tsalo** [comment]
>Do you think it would be Ok to add support for running LDA with counts_df as an input in this PR?

Sure, I think that's reasonable.

>Also, I was wondering if it would be possible to initialize and fit both the LDA and GCLDA annotators more uniformly.

Ultimately, we'll want to create an Annotator class with a standard interface (see #488 and #614), but the inits you propose look good. I haven't done a side-by-side comparison to see what you've changed, though.

>And fitting the models with fit(self, dset, counts_df=None)

That seems solid. I don't know how Annotators will look yet, so I don't have a strong opinion about this change, with the caveat that we may end up changing it once we have Annotators implemented.

BTW, the RTD CI failure is just a one-off, random thing (see #418). You can just request a rebuild and it will probably pass the next time- or at least get to a point where any _real_ bugs show up.

**Comment by JulioAPeraza** [comment]
> That seems solid. I don't know how Annotators will look yet, so I don't have a strong opinion about this change, with the caveat that we may end up changing it once we have Annotators implemented.

Sounds great! In that case, I think we can leave those changes to the PR that adds the Annotator class.

**Review by tsalo — APPROVED** [review]
Sorry for the delay. LGTM!

**Pull request merged**
