### PR TITLE
[ENH] Support symmetric GCLDA topics with more than two subregions

### LINKED ISSUE #491: Support symmetric option for even sets of regions in GCLDA
## Summary

I think it would be fairly easy to define symmetric regions as pairs instead of hardcoding region 1 and region 2 in GCLDA. This might make it easier to develop more network-based topics.

## Additional details

Network-based topics, probably?

## Next steps

1. Loop through pairs of regions in the `update_regions` method instead of matching region 1 and region 2 specifically. Each pair would have the same centroid.
2. Remove the restriction on symmetric.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #491.

Changes proposed in this pull request:

- Allow multiple symmetric pairs of subregions in GCLDA.

### CODE REVIEW

**Comment by tsalo** [comment]
@tyarkoni no pressure to review this PR in detail if you don't have the time, but I'd like to know if the general idea is, well, _bad_.

**Comment by tyarkoni** [comment]
I don't have time to review this in detail, unfortunately, but I don't see any principled problem with this, so long as the results look sane for reasonable values. Do they look sane?

**Comment by tsalo** [comment]
Thanks! The four-region results in the example look reasonable, but I will try running a more realistic version soon:

Screen Shot 2021-04-26 at 4 29 45 PM

One question- why are the paired regions' covariances estimated independently? For the "symmetric" option, wouldn't it make more sense for the regions to be symmetric not just in terms of centroid, but also in terms of skew and direction?

**Comment by tyarkoni** [comment]
Yeah that looks fine to me.

Re: symmetric covariances, I don't remember the reasoning, but I'm guessing it was probably some combination of (a) the brain isn't actually completely symmetric, and (b) in a sense it's a nice sanity check, because if the covariances look pretty similar, despite being estimated separately, that's a good sign the model is behave reasonably. But I wouldn't have any objection to parameterizing that as an option too.

**Comment by tsalo** [comment]
Thanks. I'll open an issue about a new option for symmetric covariances.

**Pull request merged**
