### PR TITLE
Add parallelization option to `CorrelationDecoder` and `CorrelationDistributionDecoder`

### PR DESCRIPTION
**Pull request by JulioAPeraza**
Closes None.

Currently, `CorrelationDecoder` takes a long time to be trained. Depending on the number of studies per feature, it takes around 13 min per feature (i.e., per iteration). For large databases like Neurosynth, which has 3228 features, it will take ~29 days. Adding the parallelization option reduces the computation time by a factor of `n_cores`. 

Changes proposed in this pull request:

- Add `n_cores` parameter to use for parallelization.

### CODE REVIEW

**Review by tsalo — APPROVED** [review]
LGTM!

**Comment by JulioAPeraza** [comment]
I would like to run another test before we merge this. The attribute `self.images_` was returned empty in one of the tests I ran yesterday.

**Comment by tsalo** [comment]
Actually, could you also fix the type at:

https://github.com/neurostuff/NiMARE/blob/245b844bd68d1bdf7685eb1b2e2b4309bcb3d5d7/nimare/decode/base.py#L80

There's an extra opening parenthesis that should be removed, but I don't think it's worth a separate PR.

**Comment by JulioAPeraza** [comment]
Sure! 
Could we also change the `vocab` in the fetch_neuroquery example to `neuroquery6308` in this PR?

**Comment by tsalo** [comment]
That would be great! Thanks!

**Comment by tsalo** [comment]
I don't know why the linter only started complaining in this PR, given that you didn't touch the problematic code, but it definitely is correct. The flagged line is definitely too long:

https://github.com/neurostuff/NiMARE/blob/87c3ce30c59382605fd141c6149be25be742be96/nimare/tests/utils.py#L26

**Comment by JulioAPeraza** [comment]
I tried splitting the summary line into two lines and it also failed the Style check test (see the last commit). Do you think we should shorten the summary sentence?

**Comment by tsalo** [comment]
That's correct. Summary sentences need to fit on one line. I think you can just drop the word "complementary" and it will fit.

**Comment by JulioAPeraza** [comment]
I think this is ready to merge. I ran a few tests locally and `self.images_` now contains the meta-analytic maps.

**Review by tsalo — APPROVED** [review]
LGTM! Feel free to merge.

**Pull request merged**
