### PR TITLE
[DOC, TST] Add tests and docs

### PR DESCRIPTION
**Pull request by tsalo**
I've started adding tests to nimare/tests/. Alternatively, I can reorganize them to module-specific folders.

We need to set up CI and coverage reports as well.

### CODE REVIEW

**Comment by tsalo** [comment]
I've merged my docs branch into tests, because they're fairly compatible sets of changes.

**Comment by tsalo** [comment]
@tyarkoni I think this PR is ready for review. Certainly coverage is probably still fairly low, but I'd like to get Travis, Coveralls, and a GitHub Pages site set up.

**Comment by tyarkoni** [comment]
Cool, will get to it as soon as I can. Might take me a while to work through, but I'm looking forward to reviewing it--looks awesome!

**Comment by tsalo** [comment]
@tyarkoni I just want to ping you about this PR. Do you think you'll be able to review it soon?

**Pull request merged**
