### PR TITLE
Support liberal mask in IBMA estimators

### PR DESCRIPTION
**Pull request by JulioAPeraza**
Closes None. Related to https://github.com/neurostuff/PyMARE/issues/44

Changes proposed in this pull request:

- Add _apply_liberal_mask to separate the data in bags of voxels in the same studies. Some parts of the proposed function require nested for loops, which was inefficient, so I have adapted some of the procedures to use numba with nopython=True.
- Currently, we loop over the bags and create a Pymare dataset. In the future, we can parallelize that loop to improve performance.

### CODE REVIEW

**Comment by JulioAPeraza** [comment]
Some preliminary results using Stouffers:
image

**Comment by tsalo** [comment]
That's so awesome! Do you have a DOF map among the outputs?

**Comment by JulioAPeraza** [comment]
We don't have them it, but that will be a great addition.

**Comment by JulioAPeraza** [comment]
Thanks @tsalo! Would that look like the figure below?

image

**Comment by tsalo** [comment]
I can't access the linked figure, unfortunately.

**Review by jdkent — CHANGES_REQUESTED** [review]
just a couple changes I requested, but otherwise LGTM, will think of possible refactor of some of the class specific bag handling to be placed in the base class.

**Review by jdkent — APPROVED** [review]
There is some potential repetitive code, but that can be refactored later, LGTM!

**Pull request merged**
