### PR TITLE
Add similarity correlation matrix figure to IBMA reports

### LINKED ISSUE #847: Add similarity-sorted correlation matrix figure to IBMA reports
## Summary

One issue with images on NeuroVault is that the contrast is not always clear or correctly labeled.
I was thinking that something that could help diagnose inverted contrasts would be a similarity-sorted correlation matrix figure, like the one in the [NARPS paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7771346/) that helped identify which processing pipelines gave inverted results to the others? It might be useful for flagging images with the wrong contrast (see below).

I don't necessarily think this would need clusters.

It could alternatively be a diagnostic of some kind.

image

### PR DESCRIPTION
**Pull request by JulioAPeraza**
Closes #847.

Changes proposed in this pull request:

- Adding a similarity-sorted correlation matrix figure to the summary section of the IBMA reports.

### CODE REVIEW

**Comment by JulioAPeraza** [comment]
Find an example here: https://nimare--852.org.readthedocs.build/en/852/auto_examples/02_meta-analyses/12_plot_ibma_workflow.html#report

**Comment by tsalo** [comment]
The figure looks great, although I'm not sure about the map sorting. What sorting method do you use?

**Comment by JulioAPeraza** [comment]
I'm using [scipy.cluster.hierarchy.linkage](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html) with the method `average` for this matrix. I found that the diagnostic table looks better with `single`. Would you suggest a different method for the correlation matrix?

Here is a figure using `complete`:

image

**Comment by JulioAPeraza** [comment]
Using `single`:

image

**Comment by tsalo** [comment]
It looks like they're the same either way. "single" sounds good. Thanks for trying it both ways!

**Review by jdkent — APPROVED** [review]
LGTM!

**Pull request merged**
