### PR TITLE
Add `save()` and `load()` methods to `MetaResult` objects

### LINKED ISSUE #770: Add `save()` and `load()` methods to `MetaResult` objects.
## Summary

@tsalo I was wondering if it would be possible to add `save()` and `load()` methods to `MetaResult` objects.

## Additional details

Having access to a `MetaResult` object will allow us to run diagnostics on results without needing to re-run an estimator and corrector. 

## Next steps

Replace `object` with `NiMAREBase` in:
https://github.com/neurostuff/NiMARE/blob/9998c7fc08cfaedbb2f9870484bc77b82ec2d0cd/nimare/results.py#L15-L17

### PR DESCRIPTION
**Pull request by JulioAPeraza**
Closes #770.

Changes proposed in this pull request:

- Pass NiMAREBase to MetaResult class to be able to save and load MetaResult objects.

### CODE REVIEW

**Review by jdkent — CHANGES_REQUESTED** [review]
LGTM, but does get_params still work with a MetaResult object?

**Comment by JulioAPeraza** [comment]
I think `MetaResult.get_params()` gives the parameter of the estimator (as a nested object) in the format `<component>__<parameter>`, and the `mask`, `maps`, and `tables` from a MetaResult object. 
Are those the expected outputs?

**Review by jdkent — APPROVED** [review]
LGTM!

**Review by tsalo — CHANGES_REQUESTED** [review]
Love this change, but can you add the new methods to one of the tests?

**Comment by JulioAPeraza** [comment]
Thanks! I've added the test to `test_meta_ale` after the saving/loading method of the estimator is tested.

**Comment by jdkent** [comment]
this looks good to merge.

**Pull request merged**
